from models import CompanyMetadata

SAMPLE_COMPANIES = [
    {
        "Company Name": "Blink Commerce Private Limited",
        "Short Name": "Blinkit",
        "Logo": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Blinkit-yellow-rounded.svg",
        "Category": "Startup",
        "Year of Incorporation": 2013,
        "Overview of the Company": "Blinkit is an Indian quick-commerce platform delivering groceries and essentials via dark stores with fast (often ~10-minute) delivery, operating across many Indian cities and owned by Zomato.",
        "Nature of Company": "Subsidiary",
        "Company Headquarters": "Gurugram-122098, Haryana, India",
        "Countries Operating In": "India",
        "Number of Offices (beyond HQ)": 25,
        "Office Locations": "Gurgaon, Mumbai, Bangalore, Hyderabad, Pune, Delhi",
        "Employee Size": "4000-5000",
        "Hiring Velocity": "High",
        "Employee Turnover": "High",
        "Average Retention Tenure": "2 years",
        "Pain Points Being Addressed": "Convenience of grocery shopping, slow delivery times in traditional e-commerce.",
        "Focus Sectors / Industries": "E-commerce, Quick Commerce",
        "Services / Offerings / Products": "Groceries, Fresh Produce, Meat, Dairy, Electronics, Beauty, Home Needs",
        "Top Customers by Client Segments": "Urban retail consumers, Millennials, Gen-Z",
        "Core Value Proposition": "Quick Commerce (~10-minute delivery), Dark Store Managed Inventory, App-based Ordering",
        "Vision": "To become the most reliable and convenient platform for all daily needs in India.",
        "Mission": "To make local commerce fast and frictionless for everyone.",
        "Values": "Speed, Innovation, Customer Obsession, Ownership, Frugality",
        "Key Competitors": "Zepto, Swiggy Instamart, BigBasket, Amazon Fresh",
        "Recent Funding Rounds": "2020-04-10 - $570,000,000 Series D Round",
        "Key Investors / Backers": "Zomato, Tiger Global, Sequoia Capital, Greenoaks",
        "LinkedIn Profile URL": "https://www.linkedin.com/company/blinkit/",
        "Regulatory & Compliance Status": "FSSAI, Consumer Protection Laws",
        "Industry Associations / Memberships": "IAMAI, FICCI",
        "Brand Sentiment Score": "Positive",
        "Net Promoter Score (NPS)": 45,
        "Glassdoor Rating": 3.5,
        "Customer Concentration Risk": "Low",
        "Burn Rate": 25000000.0
    },
    {
        "Company Name": "International Business Machines Corporation",
        "Short Name": "IBM",
        "Logo": "https://1000logos.net/wp-content/uploads/2017/02/Color-IBM-Logo.jpg",
        "Category": "Enterprise",
        "Year of Incorporation": 1911,
        "Overview of the Company": "IBM is a global technology company specializing in hybrid cloud, AI, consulting, software, and infrastructure solutions, helping businesses transform and innovate across industries.",
        "Nature of Company": "Public",
        "Company Headquarters": "Armonk, NY, United States",
        "Countries Operating In": "United States, India, United Kingdom, Germany, France, Japan, Canada",
        "Number of Offices (beyond HQ)": 300,
        "Office Locations": "Chicago, New York, London, Tokyo, Bangalore, Calgary",
        "Employee Size": "280000-300000",
        "Hiring Velocity": "Moderate",
        "Employee Turnover": "Low",
        "Average Retention Tenure": "8 years",
        "Pain Points Being Addressed": "Enterprise digital transformation, AI adoption, hybrid cloud management, IT infrastructure modernization.",
        "Focus Sectors / Industries": "Technology, Financial Services, Healthcare, Manufacturing, Government",
        "Services / Offerings / Products": "Hybrid Cloud, watsonx AI platform, IBM Z mainframes, Consulting, Storage",
        "Top Customers by Client Segments": "Fortune 500, Large Enterprises, Governments",
        "Core Value Proposition": "Trusted enterprise-grade hybrid cloud + AI, Consulting and integration capability, Security and governance.",
        "Vision": "To be the world's most successful and important information technology company.",
        "Mission": "Help clients use technology and AI to improve business outcomes through hybrid cloud, consulting, and infrastructure.",
        "Values": "Dedication to every client's success, Innovation driving progress, Trust through personal responsibility.",
        "Key Competitors": "Microsoft, Amazon Web Services, Google Cloud, Accenture, Oracle",
        "Recent Funding Rounds": None,
        "Key Investors / Backers": "Vanguard Group, BlackRock, State Street",
        "LinkedIn Profile URL": "https://www.linkedin.com/company/ibm/",
        "Regulatory & Compliance Status": "SOC, GDPR, SEC",
        "Industry Associations / Memberships": "IEEE, ACM, World Economic Forum",
        "Brand Sentiment Score": "Positive",
        "Net Promoter Score (NPS)": 50,
        "Glassdoor Rating": 4.1,
        "Customer Concentration Risk": "Low",
        "Burn Rate": 0.0
    },
    {
        "Company Name": "Barclays PLC",
        "Short Name": "Barclays",
        "Logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Barclays_Logo.svg/2560px-Barclays_Logo.svg.png",
        "Category": "Enterprise",
        "Year of Incorporation": 1896,
        "Overview of the Company": "Barclays PLC is a British multinational universal bank headquartered in London, providing personal banking, credit cards, corporate and investment banking, wealth management.",
        "Nature of Company": "Public",
        "Company Headquarters": "London, United Kingdom",
        "Countries Operating In": "United Kingdom, United States, France, Ireland, India, Germany",
        "Number of Offices (beyond HQ)": 60,
        "Office Locations": "London, New York, Mumbai, Dublin, Paris, Madrid",
        "Employee Size": "80000-90000",
        "Hiring Velocity": "Stable",
        "Employee Turnover": "Moderate",
        "Average Retention Tenure": "7.5 years",
        "Pain Points Being Addressed": "Financial management, Capital raising, Wealth preservation, Digital payment solutions.",
        "Focus Sectors / Industries": "Banking, Financial Services, Wealth Management",
        "Services / Offerings / Products": "Personal Banking, Corporate Banking, Investment Banking, Wealth Management",
        "Top Customers by Client Segments": "Individual consumers, SMEs, multinational corporations, institutional investors.",
        "Core Value Proposition": "A diversified universal bank providing specialized financial expertise across the globe with stability and innovation.",
        "Vision": "To be the bank of choice for our customers and clients, and to build a sustainable future for all.",
        "Mission": "Deploy finance responsibly to support people and businesses, acting with empathy and integrity.",
        "Values": "Respect, Integrity, Service, Excellence, Stewardship",
        "Key Competitors": "HSBC, Lloyds Banking Group, NatWest Group, JP Morgan Chase, Goldman Sachs",
        "Recent Funding Rounds": None,
        "Key Investors / Backers": "BlackRock, Vanguard, Qatar Investment Authority",
        "LinkedIn Profile URL": "https://www.linkedin.com/company/barclays/",
        "Regulatory & Compliance Status": "PRA, FCA",
        "Industry Associations / Memberships": "UK Finance, Banking Standards Board",
        "Brand Sentiment Score": "Neutral",
        "Net Promoter Score (NPS)": 35,
        "Glassdoor Rating": 3.9,
        "Customer Concentration Risk": "Low",
        "Burn Rate": 0.0
    },
    {
        "Company Name": "Schneider Electric",
        "Short Name": "Schneider Electric",
        "Logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Schneider_Electric_Logo.svg/2560px-Schneider_Electric_Logo.svg.png",
        "Category": "Enterprise",
        "Year of Incorporation": 1871,
        "Overview of the Company": "Schneider Electric is a global leader in energy management and automation, providing digital solutions for efficiency, sustainability, electrification, automation, and digitalization.",
        "Nature of Company": "Public",
        "Company Headquarters": "Rueil-Malmaison, France",
        "Countries Operating In": "France, United States, China, India, Germany",
        "Number of Offices (beyond HQ)": 150,
        "Office Locations": "Boston, Shanghai, Bangalore, Grenoble",
        "Employee Size": "150000-160000",
        "Hiring Velocity": "Stable",
        "Employee Turnover": "Low",
        "Average Retention Tenure": "10 years",
        "Pain Points Being Addressed": "Energy inefficiency, Carbon emissions, Legacy industrial automation, Data center cooling.",
        "Focus Sectors / Industries": "Energy Management, Industrial Automation, Data Centers, Infrastructure",
        "Services / Offerings / Products": "EcoStruxure platform, switchgear, PLC systems, UPS, building management systems",
        "Top Customers by Client Segments": "Major utilities, cloud service providers, industrial manufacturing, construction.",
        "Core Value Proposition": "Providing integrated digital solutions for energy and automation to achieve efficiency and sustainability.",
        "Vision": "To be your digital partner for Sustainability and Efficiency.",
        "Mission": "Combine world-leading energy technologies, real-time automation, software and services into integrated solutions.",
        "Values": "Learning, Diversity, Inclusion, Sustainability, Integrity, Empowerment",
        "Key Competitors": "Siemens, ABB, Eaton, Rockwell Automation, Emerson Electric",
        "Recent Funding Rounds": None,
        "Key Investors / Backers": "Amundi, BlackRock, Norges Bank",
        "LinkedIn Profile URL": "https://www.linkedin.com/company/schneider-electric/",
        "Regulatory & Compliance Status": "REACH, RoHS, ISO 14001",
        "Industry Associations / Memberships": "UN Global Compact, RE100, EP100",
        "Brand Sentiment Score": "Positive",
        "Net Promoter Score (NPS)": 55,
        "Glassdoor Rating": 4.1,
        "Customer Concentration Risk": "Low",
        "Burn Rate": 0.0
    }
]

import json
with open("sample_data_final.py", "w", encoding="utf-8") as f:
    f.write("SAMPLE_COMPANIES = " + json.dumps(SAMPLE_COMPANIES, indent=4) + "\n")
    print("Rewritten sample_data_final.py properly.")
