SAMPLE_COMPANIES = [
    {
        'Company Name': 'Alphabet Inc.',
        'Short Name': 'Google',
        'Logo': 'https://example.com/logo.png',
        'Category': 'Enterprise',
        'Year of Incorporation': 1998,
        'Overview of the Company': 'Google is a global technology leader providing search, advertising, cloud computing, and AI-driven business productivity tools globally.',
        'Nature of Company': 'Public',
        'Company Headquarters': 'Mountain View, CA, USA',
        'Countries Operating In': 'Worldwide',
        'Number of Offices (beyond HQ)': 70,
        'Office Locations': 'New York, London, Tokyo, Bengaluru',
        'Employee Size': '150000-200000',
        'Hiring Velocity': 'Moderate',
        'Employee Turnover': 'Low',
        'Average Retention Tenure': '5 years',
        'Pain Points Being Addressed': 'Search efficiency, cloud scalability, digital advertising, AI adoption.',
        'Focus Sectors / Industries': 'Technology, Internet, Software',
        'Services / Offerings / Products': 'Search, Cloud, Ads, YouTube, Gmail',
        'Top Customers by Client Segments': 'Consumers, SMBs, Enterprises',
        'Core Value Proposition': 'Organize the worlds information and make it universally accessible and useful.',
        'Vision': 'To provide access to the worlds information in one click.',
        'Mission': 'Our mission is to organize the worlds information and make it universally accessible and useful.',
        'Values': 'Focus on the user and all else will follow.',
        'Key Competitors': 'Microsoft, Amazon, Meta, Apple',
        'LinkedIn Profile URL': 'https://www.linkedin.com/company/google/',
        'Regulatory & Compliance Status': 'GDPR, ISO 27001',
        'Industry Associations / Memberships': 'IAMAI, W3C',
        'Brand Sentiment Score': 'Positive',
        'Net Promoter Score (NPS)': 72,
        'Glassdoor Rating': 4.5,
        'Customer Concentration Risk': 'Low',
        'Burn Rate': 0.0,
        'Recent Funding Rounds': '2004-08-19 - $1,670,000,000 Series D Round'
    },
    {
        'Company Name': 'Acme Holdings Pvt Ltd',
        'Short Name': 'Acme Holdings',
        'Logo': 'https://example.com/logo.png',
        'Category': 'SMB',
        'Year of Incorporation': 2020,
        'Overview of the Company': 'Acme Holdings is a specialized holding company providing operational excellence and strategic software solutions for modern tech businesses.',
        'Nature of Company': 'Private',
        'Company Headquarters': 'Bengaluru, India',
        'Countries Operating In': 'India',
        'Number of Offices (beyond HQ)': 3,
        'Office Locations': 'Chennai, Hyderabad',
        'Employee Size': '500-1000',
        'Hiring Velocity': 'Moderate',
        'Employee Turnover': 'Moderate',
        'Average Retention Tenure': '3 years',
        'Pain Points Being Addressed': 'Operational inefficiency, compliance complexity.',
        'Focus Sectors / Industries': 'Software, Technology, SaaS',
        'Services / Offerings / Products': 'Software Platform, Analytics',
        'Top Customers by Client Segments': 'SMBs, Mid-market',
        'Core Value Proposition': 'Scalable software that improves visibility.',
        'Vision': 'Build trusted digital infrastructure.',
        'Mission': 'Help organizations operate efficiently.',
        'Values': 'Integrity, Excellence, Innovation',
        'Key Competitors': 'Competitor A, Competitor B',
        'LinkedIn Profile URL': 'https://www.linkedin.com/company/acmeholdings/',
        'Regulatory & Compliance Status': 'SOC2, HIPAA',
        'Industry Associations / Memberships': 'NASSCOM',
        'Brand Sentiment Score': 'Neutral',
        'Net Promoter Score (NPS)': 8,
        'Glassdoor Rating': 3.1,
        'Customer Concentration Risk': 'Medium',
        'Burn Rate': 475000.5,
        'Recent Funding Rounds': '2024-03-15 - $3,500,000 Seed Round'
    },
    {
        'Company Name': 'FounderFirst Labs',
        'Short Name': 'FounderFirst',
        'Logo': 'https://example.com/logo.png',
        'Category': 'Startup',
        'Year of Incorporation': 2021,
        'Overview of the Company': 'FounderFirst is a financial technology company that provides payment processing and digital commerce infrastructure for startups.',
        'Nature of Company': 'Private',
        'Company Headquarters': 'Pune, India',
        'Countries Operating In': 'India, Singapore',
        'Number of Offices (beyond HQ)': 1,
        'Office Locations': 'Mumbai',
        'Employee Size': '10-50',
        'Hiring Velocity': 'High',
        'Employee Turnover': 'Low',
        'Average Retention Tenure': '2 years',
        'Pain Points Being Addressed': 'Payment friction, developer experience.',
        'Focus Sectors / Industries': 'FinTech, Payments',
        'Services / Offerings / Products': 'Payment APIs, Billing',
        'Top Customers by Client Segments': 'Startups, Developers',
        'Core Value Proposition': 'Frictionless payments for creators.',
        'Vision': 'Democratize global commerce.',
        'Mission': 'Increase the GDP of the internet.',
        'Values': 'Move fast, be bold.',
        'Key Competitors': 'Stripe, Razorpay',
        'LinkedIn Profile URL': 'https://www.linkedin.com/company/founderfirst/',
        'Regulatory & Compliance Status': 'PCI-DSS, AML',
        'Industry Associations / Memberships': 'IAMAI',
        'Brand Sentiment Score': 'Negative',
        'Net Promoter Score (NPS)': -35,
        'Glassdoor Rating': 1.8,
        'Customer Concentration Risk': 'High',
        'Burn Rate': 980000.75,
        'Recent Funding Rounds': '2024-03-15 - $3,500,000 Seed Round'
    },
    {
        'Company Name': 'Unicorn Labs',
        'Short Name': 'Unicorn',
        'Logo': 'https://example.com/logo.png',
        'Category': 'Startup',
        'Year of Incorporation': 2018,
        'Overview of the Company': 'Unicorn Labs is an advanced research laboratory focusing on artificial intelligence and sustainable energy solutions for the future.',
        'Nature of Company': 'Private',
        'Company Headquarters': 'Hyderabad, India',
        'Countries Operating In': 'India',
        'Number of Offices (beyond HQ)': 2,
        'Office Locations': 'Bengaluru, Delhi',
        'Employee Size': '50-200',
        'Hiring Velocity': 'High',
        'Employee Turnover': 'Low',
        'Average Retention Tenure': '4 years',
        'Pain Points Being Addressed': 'Climate change, AI safety.',
        'Focus Sectors / Industries': 'AI, Clean Energy',
        'Services / Offerings / Products': 'AI Models, Solar Software',
        'Top Customers by Client Segments': 'Governments, Research Labs',
        'Core Value Proposition': 'Innovating for a safer planet.',
        'Vision': 'A world powered by clean intelligence.',
        'Mission': 'Bridging the gap between code and climate.',
        'Values': 'Sustainability, Safety, Logic',
        'Key Competitors': 'OpenAI, Anthropic',
        'LinkedIn Profile URL': 'https://www.linkedin.com/company/unicornlabs/',
        'Regulatory & Compliance Status': 'ISO 14001, SOC2',
        'Industry Associations / Memberships': 'RE100',
        'Brand Sentiment Score': 'Positive',
        'Net Promoter Score (NPS)': 85,
        'Glassdoor Rating': 4.8,
        'Customer Concentration Risk': 'High',
        'Burn Rate': 150000.0,
        'Recent Funding Rounds': '2024-03-15 - $3,500,000 Seed Round'
    },
    {
        'Company Name': 'GeoRisk Systems Pvt Ltd',
        'Short Name': 'GeoRisk',
        'Logo': 'https://example.com/logo.png',
        'Category': 'Startup',
        'Year of Incorporation': 2022,
        'Overview of the Company': 'GeoRisk Systems provides real-time geospatial analysis and risk assessment tools for infrastructure projects worldwide.',
        'Nature of Company': 'Private',
        'Company Headquarters': 'Gurugram, India',
        'Countries Operating In': 'Worldwide',
        'Number of Offices (beyond HQ)': 1,
        'Office Locations': 'London',
        'Employee Size': '20-50',
        'Hiring Velocity': 'Moderate',
        'Employee Turnover': 'Low',
        'Average Retention Tenure': '2 years',
        'Pain Points Being Addressed': 'Infrastructure project delays, geospatial uncertainty.',
        'Focus Sectors / Industries': 'Geospatial, Software',
        'Services / Offerings / Products': 'Risk API, Mapping Dashboard',
        'Top Customers by Client Segments': 'Construction Companies, NGOs',
        'Core Value Proposition': 'Navigate geospatial risks with precision.',
        'Vision': 'Mapping the future safely.',
        'Mission': 'Provide actionable insights for global infrastructure.',
        'Values': 'Accuracy, Transparency',
        'Key Competitors': 'Esri, Mapbox',
        'LinkedIn Profile URL': 'https://www.linkedin.com/company/georisk/',
        'Regulatory & Compliance Status': 'GDPR, ISO 9001',
        'Industry Associations / Memberships': 'OGC',
        'Brand Sentiment Score': 'Positive',
        'Net Promoter Score (NPS)': 35,
        'Glassdoor Rating': 4.0,
        'Customer Concentration Risk': 'Low',
        'Burn Rate': 250000.0,
        'Recent Funding Rounds': '2024-03-15 - $3,500,000 Seed Round'
    }
]
